# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  yml-md-style-and-link-checks:
    uses: QubitPi/hashicorp-aws/.github/workflows/yml-md-style-and-link-checks.yml@master

  test-upversion:
    name: Test upversion.py
    outputs:
      outcome: ${{ job.status }}
    continue-on-error: true
    needs: yml-md-style-and-link-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "LAST_TAG=1.2.3" >> $GITHUB_ENV
      - run: |
          NEW_TAG=$(LAST_TAG=${LAST_TAG} python upversion.py)
          if [[ "$NEW_TAG" != "1.2.4" ]]; then
              exit 1
          fi

  slack-notification:
    name: Send Slack Notification
    if: ${{ always() }}
    needs: test-upversion
    uses: QubitPi/hashicorp-aws/.github/workflows/slack-notification.yml@master
    with:
      job-status: ${{ needs.test-upversion.outputs.outcome }}
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
